services:
  stablesats-pg:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pg

# We try a local integration tests before adding this complexity
# It's easier to maintain and works thanks to nix and direnv
# But maybe we'l return to this approach nevertheless
# Keeping that here until we have a workable CI pipeline build
  # integration-tests:
  #   image: us.gcr.io/galoy-org/rust-concourse
  #   depends_on:
  #   - integration-deps
  #   command: ["make","test-in-ci"]
  #   env_file:
  #     - ${TMP_ENV_CI:-.env.ci}
  #   environment:
  #   - RUST_BACKTRACE=1
  #   - PG_HOST=stablesats-pg
  #   - PG_PORT=5432
  #   - BRIA_URL=http://bria:2742
  #   - GALOY_GRAPHQL_URI=https://api.staging.galoy.io/graphql
  #   working_dir: /repo
  #   volumes:
  #     - ../../:/repo
  #     - cargo-cache:/usr/local/cargo

volumes:
  cargo-cache:
