services:
  otel-agent:
    ports:
    - "4318:4318"
  kratos-pg:
    ports:
    - 5439:5432
  stablesats-pg:
    ports:
    - "5440:5432"
  bria:
    ports:
    - "2743:2743"
    - "2742:2742"
  bitcoind:
    ports:
      - "18443:18443"
  bitcoind-signer:
    ports:
      - "18543:18443"
  fulcrum:
    ports:
      - "50001:50001"
  stablesats:
    # Disable the stablesats container to run local development version
    deploy:
      replicas: 0
