apiVersion: vendir.k14s.io/v1alpha1
kind: Config

directories:
  - path: vendor
    contents:
      - path: blink-quickstart
        git:
          url: https://github.com/blinkbitcoin/blink.git
          ref: 'main'
        includePaths:
          - quickstart/.env.galoy
          - quickstart/docker-compose.yml
          - quickstart/dev/**/*
          - quickstart/graphql/**/*
          - quickstart/galoy/test/**/*
          - quickstart/bin/*
          - quickstart/.gitignore
        newRootPath: quickstart
