[package]
name = "stablesats"
version = "0.12.9-dev"
edition = "2021"
authors = ["Justin Carter <justin@galoy.io>"]
license = "MIT"
repository = "https://github.com/GaloyMoney/stablesats-rs"
description = "The stablesats cli binary"

[features]

fail-on-warnings = []

[dependencies]
shared = { path = "../shared", package = "stablesats-shared" }
price-server = { path = "../price-server" }
quotes-server = { path = "../quotes-server" }
user-trades = { path = "../user-trades" }
galoy-client = { path = "../galoy-client" }
okex-client = { path = "../okex-client" }
hedging = { path = "../hedging" }
okex-price = { path = "../okex-price" }
bria-client = { path = "../bria-client" }
ledger = { path = "../ledger", package = "stablesats-ledger" }

anyhow = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
tonic = { workspace = true }
url = { workspace = true }
rust_decimal = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry_sdk = { workspace = true }
opentelemetry-otlp = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-opentelemetry = { workspace = true }
axum = { workspace = true }
chrono = { workspace = true }
sqlx = { workspace = true }
serde_json = { workspace = true }
