apiVersion: vendir.k14s.io/v1alpha1
kind: Config

# Relative to ci/
directories:
- path: ../.github/workflows/vendor
  contents:
  - path: . # Copy this folder out to ..
    git:
      url: https://github.com/blinkbitcoin/concourse-shared.git
      ref: db4367880f3716b0e8f37c6e651c7c115f08ff8a
    includePaths:
    - shared/actions/*
    excludePaths:
    - shared/actions/nodejs-*
    - shared/actions/tofu-*
    newRootPath: shared/actions

- path: ./vendor
  contents:
  - path: .
    git:
      url: https://github.com/blinkbitcoin/concourse-shared.git
      ref: db4367880f3716b0e8f37c6e651c7c115f08ff8a
    includePaths:
    - shared/ci/**/*
    excludePaths:
    - shared/ci/**/nodejs-*
    - shared/ci/**/tofu-*
    newRootPath: shared/ci

- path: ../bin/vendor
  contents:
  - path: .
    git:
      url: https://github.com/blinkbitcoin/concourse-shared.git
      ref: db4367880f3716b0e8f37c6e651c7c115f08ff8a
    includePaths:
    - shared/bin/**/*
    excludePaths:
    - shared/bin/**/nodejs-*
    - shared/bin/**/tofu-*
    newRootPath: shared/bin

