name: "Integration Tests"

on:
  pull_request:
    branches: [ main ]

jobs:
  integration:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run integration tests
        env:
          OKEX_API_KEY: ${{ secrets.OKEX_API_KEY }}
          OKEX_PASSPHRASE: ${{ secrets.OKEX_PASSPHRASE }}
          OKEX_SECRET_KEY: ${{ secrets.OKEX_SECRET_KEY }}
          BITFINEX_API_KEY: ${{ secrets.BITFINEX_API_KEY }}
          BITFINEX_SECRET_KEY: ${{ secrets.BITFINEX_SECRET_KEY }}
          GALOY_PHONE_CODE: ${{ secrets.GALOY_PHONE_CODE }}
          GALOY_PHONE_NUMBER: ${{ secrets.GALOY_PHONE_NUMBER }}
        run: dev/bin/tilt-ci.sh
